### PR TITLE
Added Breakpoint Hook + Apply Page JSX Cleanup

### PR DESCRIPTION
**Pull request by Yonava**
* Better Modularization on Apply JSX
* Added hooks dir and created useBreakpoint hook for reactive mdi spec breakpoints
* Removed lots of unnecessary nesting
* Created sub dir inside of components for page specific components
* Created "contents" dir to better organize text blobs for each page

### CODE REVIEW

**Comment by Yonava** [comment]
@weebao if you dont want to be on these prs let me know and I will take you off. Just want someone looking over my shoulder before I commit too many changes to the site.

**Comment by weebao** [comment]
> @weebao if you dont want to be on these prs let me know and I will take you off. Just want someone looking over my shoulder before I commit too many changes to the site.

All good man I appreciate you doing that

**Review by weebao — COMMENTED** [review]
LGTM! For particles.js, we are using an old version so the particles would get laggy if we click too much. Can you also look for a way to update it or change it somehow?

Also, can you change the max-width of two cards in the `apply` site below the "The application window for spring 2024..." to 360px for better readability if you have time.

Thanks Yona!

**Comment by Yonava** [comment]
> LGTM! For particles.js, we are using an old version so the particles would get laggy if we click too much. Can you also look for a way to update it or change it somehow?
> 
> Also, can you change the max-width of two cards in the `apply` site below the "The application window for spring 2024..." to 360px for better readability if you have time.
> 
> Thanks Yona!

I will look into updating the particle lib. Can you create an issue for it so it can go on the backlog?

**Review by weebao — APPROVED** [review]
LGTM. Thanks for the work Yona!

**Pull request merged**
